### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PyCharm

### Create user
PUT http://localhost:8000/users/
Content-Type: application/json

{
    "auth0_id": "auth0|abc123xyz",
    "name": "John Doe",
    "email": "johndoe@example.com",
    "role": "volunteer",
    "total_points": 0
}

### Get users
GET http://localhost:8000/users/

### Get user
GET http://localhost:8000/users/1

### Update user
PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "name": "Johnny Doe",
    "email": "johnnydoe@example.com",
    "role": "organizer",
    "total_points": 50
}

### Delete user
DELETE http://localhost:8000/users/1

