### Signup
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
  "email":"johndoe3@example.com",
  "password":"StrongPass123!"
}

### Login
POST http://localhost:8000/auth/login
Content-Type: application/x-www-form-urlencoded

username=johndoe2@example.com&password=StrongPass123!
